(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.intern('DIV-BANNER');
var l2=internals.make_lisp_string('div');
var l3=internals.intern('NIL','COMMON-LISP');
var l4=internals.QIList(internals.make_lisp_string('id'),internals.make_lisp_string('class'),l3);
var l5=internals.QIList(internals.make_lisp_string('banner-id'),internals.make_lisp_string('tide-banner tide-default-font'),l3);
var l6=internals.intern('PAIR');
var l7=internals.intern('DOM-CREATE');
l1.value=l7.fvalue(internals.pv,l2,l6.fvalue(internals.pv,l4,l5));
l1;
var l8=internals.intern('DIV-CONSOLE');
var l9=internals.make_lisp_string('div');
var l10=internals.QIList(internals.make_lisp_string('id'),internals.make_lisp_string('class'),l3);
var l11=internals.QIList(internals.make_lisp_string('console-id'),internals.make_lisp_string('tide-console tide-default-font'),l3);
l8.value=l7.fvalue(internals.pv,l9,l6.fvalue(internals.pv,l10,l11));
l8;
var l12=internals.intern('DIV-SELECT');
var l13=internals.make_lisp_string('div');
var l14=internals.QIList(internals.make_lisp_string('id'),internals.make_lisp_string('class'),l3);
var l15=internals.QIList(internals.make_lisp_string('select-id'),internals.make_lisp_string('tide-canvas'),l3);
l12.value=l7.fvalue(internals.pv,l13,l6.fvalue(internals.pv,l14,l15));
l12;
var l16=internals.intern('DIV-CONTROL');
var l17=internals.make_lisp_string('div');
var l18=internals.QIList(internals.make_lisp_string('id'),internals.make_lisp_string('class'),l3);
var l19=internals.QIList(internals.make_lisp_string('control-tab-id'),internals.make_lisp_string('tide-control-pad tide-default-font'),l3);
l16.value=l7.fvalue(internals.pv,l17,l6.fvalue(internals.pv,l18,l19));
l16;
var l20=internals.intern('BR-DIV');
var l21=internals.make_lisp_string('br');
l20.value=l7.fvalue(internals.pv,l21);
l20;
var l22=internals.intern('SPACE-DIV');
var l23=internals.make_lisp_string('|  |');
var l24=internals.intern('DOM-CREATE-TEXT-NODE');
l22.value=l24.fvalue(internals.pv,l23);
l22;
var l25=internals.intern('TIDE-MOUNT');
var l26=internals.intern('DOM-GET-BODY');
var l27=internals.intern('DOM-MOUNT');
l25.fvalue=(function(){var FUNC=(function JSCL_USER_TIDEMOUNT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v1=this;
return (function(){return l27.fvalue(values,l26.fvalue(internals.pv),internals.symbolValue(l1),internals.symbolValue(l12),internals.symbolValue(l8),internals.symbolValue(l16));
})();
});
FUNC.fname='TIDE-MOUNT';
return FUNC;
})();
l25;
var l28=internals.intern('%TIDE-CONSOLE-WRITE');
var l29=internals.make_lisp_string('<br>');
var l30=internals.intern('DOM-APPEND');
l28.fvalue=(function(){var FUNC=(function JSCL_USER_TIDECONSOLEWRITE(values,v3){internals.checkArgs(arguments.length-1,1);
var v4=this;
return (function(){return (function(){var v6=l24.fvalue(internals.pv,v3);
return l30.fvalue(values,internals.symbolValue(l8),v6,l29);
})();
})();
});
FUNC.fname='%TIDE-CONSOLE-WRITE';
return FUNC;
})();
l28;
var l31=internals.intern('%TIDE-CONSOLE-CHAR');
var l32=internals.intern('STRING','COMMON-LISP');
var l33=internals.intern('EQUAL','COMMON-LISP');
var l34=internals.make_lisp_string('<br>');
l31.fvalue=(function(){var FUNC=(function JSCL_USER_TIDECONSOLECHAR(values,v7){internals.checkArgs(arguments.length-1,1);
var v8=this;
return (function(){return (function(){var v10=l32.fvalue(internals.pv,v7);
if (l33.fvalue(internals.pv,v7,'\n')!==l3.value) (function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v12){switch(arguments.length-1){case 0:v12=l3.value;
;
default:break;
}var v11=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v11=new internals.Cons(arguments[I+1],v11);
var v13=this;
return v10=v12;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l34;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else l3.value;
return l30.fvalue(values,internals.symbolValue(l8),v10);
})();
})();
});
FUNC.fname='%TIDE-CONSOLE-CHAR';
return FUNC;
})();
l31;
var l35=internals.intern('%TIDE-CONSOLE-CHAR-1');
l35.fvalue=(function(){var FUNC=(function JSCL_USER_TIDECONSOLECHAR(values,v14){internals.checkArgs(arguments.length-1,1);
var v15=this;
return (function(){return l30.fvalue(values,internals.symbolValue(l8),l32.fvalue(internals.pv,v14));
})();
});
FUNC.fname='%TIDE-CONSOLE-CHAR-1';
return FUNC;
})();
l35;
var l36=internals.intern('BANNER-MSG');
var l37=internals.QIList(l36,l3);
var l38=internals.intern('EXPORT','COMMON-LISP');
l38.fvalue(internals.pv,l37);
var l39=internals.make_lisp_string('<strong  style="color:red;">~a</strong>');
var l40=internals.make_lisp_string('<font style="color:red">~a</font>');
var l41=internals.make_lisp_string('<strong style="color:orange;">~a</strong>');
var l42=internals.make_lisp_string('<font style="color:orange">~a</font>');
var l43=internals.make_lisp_string('<strong style="color:green;">~a</strong>');
var l44=internals.make_lisp_string('<font style="color:green">~a</font>');
var l45=internals.intern('LIST','COMMON-LISP');
var l46=internals.intern('ELT','COMMON-LISP');
var l47=internals.intern('FORMAT','COMMON-LISP');
var l48=internals.intern('DOM-SET-INNER-HTML');
l36.fvalue=(function(){var FUNC=(function JSCL_USER_BANNERMSG(values,v17,v18){internals.checkArgs(arguments.length-1,2);
var v19=this;
return (function(){return (function(){var v21=l45.fvalue(internals.pv,l39,l40,l41,l42,l43,l44);
l48.fvalue(internals.pv,internals.symbolValue(l1),l47.fvalue(internals.pv,l3.value,l46.fvalue(internals.pv,v21,v17),v18));
return values();
})();
})();
});
FUNC.fname='BANNER-MSG';
return FUNC;
})();
l36;
var l49=internals.intern('TIDE-WELCOME');
var l50=internals.intern('*ROOT*');
var l51=internals.make_lisp_string('window');
var l52=internals.make_lisp_string('navigator');
var l53=internals.make_lisp_string('userAgent');
var l54=internals.make_lisp_string('window');
var l55=internals.make_lisp_string('navigator');
var l56=internals.make_lisp_string('hardwareConcurrency');
var l57=internals.make_lisp_string('window');
var l58=internals.make_lisp_string('navigator');
var l59=internals.make_lisp_string('onLine');
var l60=internals.make_lisp_string('<strong style="color:orange">Welcome JSCL console.</strong><br>');
var l61=internals.make_lisp_string('<font style="color:orange">Platform: ~a CPU:~a Online:~a</font><br>');
var l62=internals.make_lisp_string('<font style="color:orange">Type (man "man") for read manual');
var l63=internals.intern('CONCAT');
l49.fvalue=(function(){var FUNC=(function JSCL_USER_TIDEWELCOME(values){internals.checkArgsAtMost(arguments.length-1,0);
var v22=this;
return (function(){return (function(){var v24=internals.js_to_lisp((function(){var TMP=internals.symbolValue(l50)[internals.xstring(l51)];
if (TMP===undefined) return l3.value;
TMP=TMP[internals.xstring(l52)];
if (TMP===undefined) return l3.value;
TMP=TMP[internals.xstring(l53)];
return TMP===undefined?l3.value:TMP;
})());
var v25=internals.js_to_lisp((function(){var TMP=internals.symbolValue(l50)[internals.xstring(l54)];
if (TMP===undefined) return l3.value;
TMP=TMP[internals.xstring(l55)];
if (TMP===undefined) return l3.value;
TMP=TMP[internals.xstring(l56)];
return TMP===undefined?l3.value:TMP;
})());
var v26=internals.js_to_lisp((function(){var TMP=internals.symbolValue(l50)[internals.xstring(l57)];
if (TMP===undefined) return l3.value;
TMP=TMP[internals.xstring(l58)];
if (TMP===undefined) return l3.value;
TMP=TMP[internals.xstring(l59)];
return TMP===undefined?l3.value:TMP;
})());
return l48.fvalue(values,internals.symbolValue(l1),l47.fvalue(internals.pv,l3.value,l63.fvalue(internals.pv,l60,l61,l62),v24,v25,v26));
})();
})();
});
FUNC.fname='TIDE-WELCOME';
return FUNC;
})();
l49;
var l64=internals.intern('%WRITE-STRING');
var l65=internals.intern('T','COMMON-LISP');
var l66=internals.make_lisp_string('jqconsole');
var l67=internals.make_lisp_string('jqconsole-output');
var l68=internals.make_lisp_string('');
var l69=internals.make_lisp_string('jqconsole');
var l70=internals.make_lisp_string('Write');
var l71=internals.make_lisp_string('console');
var l72=internals.make_lisp_string('log');
l64.fvalue=(function(){var FUNC=(function JSCL_USER_WRITESTRING(values,v27,v28){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v28=l65.value;
;
default:break;
}var v29=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l50)[internals.xstring(l66)];
return TMP===undefined?l3.value:TMP;
})())!==l3.value?internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l69)][internals.xstring(l70)](internals.lisp_to_js(v27),internals.lisp_to_js(l67),internals.lisp_to_js(l68),internals.lisp_to_js(v28))):internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l71)][internals.xstring(l72)](internals.lisp_to_js(v27)));
})();
});
FUNC.fname='%WRITE-STRING';
return FUNC;
})();
l64;
var l73=internals.intern('LOAD-HISTORY');
var l74=internals.make_lisp_string('jqhist');
var l75=internals.make_lisp_string('localStorage');
var l76=internals.make_lisp_string('getItem');
var l77=internals.make_lisp_string('JSON');
var l78=internals.make_lisp_string('parse');
var l79=internals.make_lisp_string('jqconsole');
var l80=internals.make_lisp_string('SetHistory');
l73.fvalue=(function(){var FUNC=(function JSCL_USER_LOADHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v31=this;
return (function(){return (function(v33){return (v33===null?l65.value:l3.value)!==l3.value?l3.value:internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l79)][internals.xstring(l80)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l77)][internals.xstring(l78)](internals.lisp_to_js(v33))))));
})(internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l75)][internals.xstring(l76)](internals.lisp_to_js(l74))));
})();
});
FUNC.fname='LOAD-HISTORY';
return FUNC;
})();
l73;
var l81=internals.intern('SAVE-HISTORY');
var l82=internals.make_lisp_string('jqhist');
var l83=internals.make_lisp_string('jqconsole');
var l84=internals.make_lisp_string('GetHistory');
var l85=internals.make_lisp_string('JSON');
var l86=internals.make_lisp_string('stringify');
var l87=internals.make_lisp_string('localStorage');
var l88=internals.make_lisp_string('setItem');
l81.fvalue=(function(){var FUNC=(function JSCL_USER_SAVEHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v34=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l87)][internals.xstring(l88)](internals.lisp_to_js(l82),internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l85)][internals.xstring(l86)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l83)][internals.xstring(l84)]())))))));
})();
});
FUNC.fname='SAVE-HISTORY';
return FUNC;
})();
l81;
var l89=internals.intern('TIDE-JQ-HISTORY');
l89.value=l3.value;
l89;
var l90=internals.intern('TAKE-CONSOLE-HISTORY');
var l91=internals.QIList(l90,l3);
l38.fvalue(internals.pv,l91);
var l92=internals.make_lisp_string('jqhist');
var l93=internals.make_lisp_string('localStorage');
var l94=internals.make_lisp_string('getItem');
var l95=internals.make_lisp_string('JSON');
var l96=internals.make_lisp_string('parse');
var l97=internals.intern('LENGTH','COMMON-LISP');
var l98=internals.make_lisp_string('<br>History has ~a items');
l90.fvalue=(function(){var FUNC=(function JSCL_USER_TAKECONSOLEHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v36=this;
return (function(){return (function(v38,v39){if ((v38===null?l65.value:l3.value)!==l3.value) l3.value;
 else {(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v41){switch(arguments.length-1){case 0:v41=l3.value;
;
default:break;
}var v40=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v40=new internals.Cons(arguments[I+1],v40);
var v42=this;
return l89.value=v41;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l95)][internals.xstring(l96)](internals.lisp_to_js(v38)));
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v44){switch(arguments.length-1){case 0:v44=l3.value;
;
default:break;
}var v43=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v43=new internals.Cons(arguments[I+1],v43);
var v45=this;
return v38=v44;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v47){switch(arguments.length-1){case 0:v47=l3.value;
;
default:break;
}var v46=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v46=new internals.Cons(arguments[I+1],v46);
var v48=this;
return v39=v47;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l97.fvalue(values,internals.symbolValue(l89));
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
}l36.fvalue(internals.pv,4,l47.fvalue(internals.pv,l3.value,l98,v39));
return values();
})(internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l93)][internals.xstring(l94)](internals.lisp_to_js(l92))),0);
})();
});
FUNC.fname='TAKE-CONSOLE-HISTORY';
return FUNC;
})();
l90;
var l99=internals.intern('LOOK-CONSOLE-HISTORY');
var l100=internals.QIList(l99,l3);
l38.fvalue(internals.pv,l100);
var l101=internals.intern('1-','COMMON-LISP');
var l102=internals.make_lisp_string('~a: ~s~%');
var l103=internals.intern('AREF','COMMON-LISP');
var l104=internals.intern('1+','COMMON-LISP');
l99.fvalue=(function(){var FUNC=(function JSCL_USER_LOOKCONSOLEHISTORY(values,v49,v50){internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 0:v49=0;
;
case 1:v50=5;
;
default:break;
}var v51=this;
return (function(){return (function(v53){if ((function(){var x1=v53;
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l65.value:l3.value;
})()!==l3.value) (function(v54,v55){return (function(){return (function(){var v57=1;
var v58=[];
TBLOOP:while (true){try{switch(v57){case 1:if ((function(){var x1=v54;
if (typeof x1!='number') throw 'Not a number!';
var x2=v55;
if (typeof x2!='number') throw 'Not a number!';
return x1>x2?l65.value:l3.value;
})()!==l3.value) (function(){throw new internals.TagNLX(v58,2);
})();
 else l3.value;
l47.fvalue(internals.pv,l65.value,l102,v54,l32.fvalue(internals.pv,l103.fvalue(internals.pv,internals.symbolValue(l89),v54)));
v54=l104.fvalue(internals.pv,v54);
(function(){throw new internals.TagNLX(v58,1);
})();
case 2:default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v58) v57=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})();
})(v49,(function(){var x1=v50;
if (typeof x1!='number') throw 'Not a number!';
var x2=v53;
if (typeof x2!='number') throw 'Not a number!';
return x1>=x2?l65.value:l3.value;
})()!==l3.value?l101.fvalue(internals.pv,v53):v50);
 else l3.value;
return values();
})(l97.fvalue(internals.pv,internals.symbolValue(l89)));
})();
});
FUNC.fname='LOOK-CONSOLE-HISTORY';
return FUNC;
})();
l99;
var l105=internals.intern('TAKE-HISTORY-ITEM');
var l106=internals.QIList(l105,l3);
l38.fvalue(internals.pv,l106);
var l107=internals.make_lisp_string('jqconsole');
var l108=internals.make_lisp_string('state');
var l109=internals.make_lisp_string('jqconsole');
var l110=internals.make_lisp_string('state');
var l111=internals.make_lisp_string('jqconsole');
var l112=internals.make_lisp_string('SetPromptText');
var l113=internals.make_lisp_string('jqconsole');
var l114=internals.make_lisp_string('state');
l105.fvalue=(function(){var FUNC=(function JSCL_USER_TAKEHISTORYITEM(values,v59){internals.checkArgs(arguments.length-1,1);
var v60=this;
return (function(){return (function(v62){(function(){var v63=internals.symbolValue(l50);
var v64=l109;
var v65=l110;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v67){switch(arguments.length-1){case 0:v67=l3.value;
;
default:break;
}var v66=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v66=new internals.Cons(arguments[I+1],v66);
var v68=this;
return (function(){var OBJ=v63;
OBJ=OBJ[internals.xstring(v64)];
if (OBJ===undefined) throw 'Impossible to set object property.';
var TMP=(OBJ[internals.xstring(v65)]=internals.lisp_to_js(v67));
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=0;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l111)][internals.xstring(l112)](internals.lisp_to_js(l103.fvalue(internals.pv,internals.symbolValue(l89),v59))));
(function(){var v69=internals.symbolValue(l50);
var v70=l113;
var v71=l114;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v73){switch(arguments.length-1){case 0:v73=l3.value;
;
default:break;
}var v72=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v72=new internals.Cons(arguments[I+1],v72);
var v74=this;
return (function(){var OBJ=v69;
OBJ=OBJ[internals.xstring(v70)];
if (OBJ===undefined) throw 'Impossible to set object property.';
var TMP=(OBJ[internals.xstring(v71)]=internals.lisp_to_js(v73));
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v62;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return values();
})(internals.js_to_lisp((function(){var TMP=internals.symbolValue(l50)[internals.xstring(l107)];
if (TMP===undefined) return l3.value;
TMP=TMP[internals.xstring(l108)];
return TMP===undefined?l3.value:TMP;
})()));
})();
});
FUNC.fname='TAKE-HISTORY-ITEM';
return FUNC;
})();
l105;
var l115=internals.intern('CTRL-BTN-RESET-HIST');
var l116=internals.make_lisp_string('RST');
var l117=internals.QIList(internals.make_lisp_string('id'),internals.make_lisp_string('class'),l3);
var l118=internals.QIList(internals.make_lisp_string('ctrl- rst-button-id'),internals.make_lisp_string('tide-button '),l3);
var l119=internals.make_lisp_string('onclick');
var l120=internals.make_lisp_string('jqconsole');
var l121=internals.make_lisp_string('ResetHistory');
var l122=internals.make_lisp_string('<br>Console history reset');
var l123=internals.intern('DOM-CREATE-BUTTON');
l115.value=l123.fvalue(internals.pv,l116,l6.fvalue(internals.pv,l117,l118),l45.fvalue(internals.pv,new internals.Cons(l119,(function JSCL_USER_NIL(values,v75){internals.checkArgs(arguments.length-1,1);
var v76=this;
internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l120)][internals.xstring(l121)]());
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v78){switch(arguments.length-1){case 0:v78=l3.value;
;
default:break;
}var v77=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v77=new internals.Cons(arguments[I+1],v77);
var v79=this;
return l89.value=v78;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l36.fvalue(internals.pv,4,l47.fvalue(internals.pv,l3.value,l122));
return values();
}))));
l115;
var l124=internals.intern('RESET-BTN-ON');
var l125=internals.QIList(l124,l3);
l38.fvalue(internals.pv,l125);
l124.fvalue=(function(){var FUNC=(function JSCL_USER_RESETBTNON(values){internals.checkArgsAtMost(arguments.length-1,0);
var v80=this;
return (function(){l27.fvalue(internals.pv,internals.symbolValue(l16),internals.symbolValue(l115));
return values();
})();
});
FUNC.fname='RESET-BTN-ON';
return FUNC;
})();
l124;
var l126=internals.intern('RESET-BTN-OFF');
var l127=internals.QIList(l126,l3);
l38.fvalue(internals.pv,l127);
var l128=internals.intern('DOM-REMOVE');
l126.fvalue=(function(){var FUNC=(function JSCL_USER_RESETBTNOFF(values){internals.checkArgsAtMost(arguments.length-1,0);
var v82=this;
return (function(){l128.fvalue(internals.pv,internals.symbolValue(l115));
return values();
})();
});
FUNC.fname='RESET-BTN-OFF';
return FUNC;
})();
l126;
var l129=internals.intern('RESET-JQ-SHORTCUTS');
var l130=internals.QIList(l129,l3);
l38.fvalue(internals.pv,l130);
var l131=internals.make_lisp_string('jqconsole');
var l132=internals.make_lisp_string('ResetShortcuts');
l129.fvalue=(function(){var FUNC=(function JSCL_USER_RESETJQSHORTCUTS(values){internals.checkArgsAtMost(arguments.length-1,0);
var v84=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l131)][internals.xstring(l132)]());
})();
});
FUNC.fname='RESET-JQ-SHORTCUTS';
return FUNC;
})();
l129;
var l133=internals.intern('DOM-JQ-CLEANER-TIMER');
l133.value=l3.value;
l133;
var l134=internals.intern('DOM-JQ-CLEANER-RUN');
l134.value=l3.value;
l134;
var l135=internals.intern('*DOM-JQ-CLR-CLASSES');
var l136=internals.QIList(l135,l3);
l38.fvalue(internals.pv,l136);
var l137=internals.make_lisp_string('.jqconsole-output');
var l138=internals.make_lisp_string('.jqconsole-prompt');
var l139=internals.make_lisp_string('.jqconsole-old-prompt');
var l140=internals.make_lisp_string('.jqconsole-error');
var l141=internals.make_lisp_string('.jqconsole-return');
l135.value=l45.fvalue(internals.pv,l137,l138,l139,l140,l141);
l135;
var l142=internals.intern('DOM-CLEANER');
var l143=internals.QIList(l142,l3);
l38.fvalue(internals.pv,l143);
var l144=internals.make_lisp_string('.jqconsole-output');
var l145=internals.make_lisp_string('jqconsole');
var l146=internals.make_lisp_string('$container');
var l147=internals.make_lisp_string('find');
var l148=internals.intern('ASET');
l142.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCLEANER(values,v86){internals.checkArgsAtMost(arguments.length-1,1);
switch(arguments.length-1){case 0:v86=l144;
;
default:break;
}var v87=this;
return (function(){return (function(){var v89=internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l145)][internals.xstring(l146)][internals.xstring(l147)](internals.lisp_to_js(v86)));
var v90=l97.fvalue(internals.pv,v89);
var v91=(function(){var x1=v90;
if (typeof x1!='number') throw 'Not a number!';
return x1-100;
})();
var v92=0;
if ((function(){var x1=v91;
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l65.value:l3.value;
})()!==l3.value) {(function(){return (function(v94,v95){(function(){while ((function(){var x1=v94;
if (typeof x1!='number') throw 'Not a number!';
var x2=v95;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l65.value:l3.value;
})()!==l3.value){l128.fvalue(internals.pv,l103.fvalue(internals.pv,v89,v94));
(function(){var v96=v89;
var v97=v94;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v99){switch(arguments.length-1){case 0:v99=l3.value;
;
default:break;
}var v98=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v98=new internals.Cons(arguments[I+1],v98);
var v100=this;
return l148.fvalue(values,v96,v97,v99);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l3.value;
(function(){var v101=1;
var v102=(function(){var x1=v94;
if (typeof x1!='number') throw 'Not a number!';
var x2=v101;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v94=v102;
})();
}return l3.value;
})();
return l3.value;
})(0,v91);
})();
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v104){switch(arguments.length-1){case 0:v104=l3.value;
;
default:break;
}var v103=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v103=new internals.Cons(arguments[I+1],v103);
var v105=this;
return v92=v104;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v91;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
} else l3.value;
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v107){switch(arguments.length-1){case 0:v107=l3.value;
;
default:break;
}var v106=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v106=new internals.Cons(arguments[I+1],v106);
var v108=this;
return v89=v107;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return v92;
})();
})();
});
FUNC.fname='DOM-CLEANER';
return FUNC;
})();
l142;
var l149=internals.intern('DOM-CLEANER-TOP');
var l150=internals.QIList(l149,l3);
l38.fvalue(internals.pv,l150);
var l151=[0,0,0,0,0];
var l152=internals.make_lisp_string('<br>CLR ~a~%');
l149.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCLEANERTOP(values){internals.checkArgsAtMost(arguments.length-1,0);
var v109=this;
return (function(){return (function(v111,v112,v113){(function(){return (function(v115,v116){(function(){while (v115!==l3.value){v116=internals.car(v115);
(function(){var v117=(function(){var v118=v111;
var v119=v112;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v121){switch(arguments.length-1){case 0:v121=l3.value;
;
default:break;
}var v120=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v120=new internals.Cons(arguments[I+1],v120);
var v122=this;
return l148.fvalue(values,v118,v119,v121);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l142.fvalue(values,v116);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
var v123=(function(){var x1=v113;
if (typeof x1!='number') throw 'Not a number!';
var x2=v117;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v113=v123;
})();
(function(){var v124=1;
var v125=(function(){var x1=v112;
if (typeof x1!='number') throw 'Not a number!';
var x2=v124;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v112=v125;
})();
l3.value;
v115=internals.cdr(v115);
}return l3.value;
})();
return l3.value;
})(internals.symbolValue(l135),l3.value);
})();
if ((function(){var x1=v113;
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l65.value:l3.value;
})()!==l3.value) l36.fvalue(internals.pv,2,l47.fvalue(internals.pv,l3.value,l152,v111));
 else l3.value;
return values();
})(l151,0,0);
})();
});
FUNC.fname='DOM-CLEANER-TOP';
return FUNC;
})();
l149;
var l153=internals.intern('DOM-JQ-CLEANER-SWITCH');
var l154=internals.make_lisp_string('window');
var l155=internals.make_lisp_string('clearTimeout');
var l156=internals.make_lisp_string('<br>CLR OFF');
var l157=internals.make_lisp_string('window');
var l158=internals.make_lisp_string('setInterval');
var l159=internals.make_lisp_string('<br>CLR ON');
l153.fvalue=(function(){var FUNC=(function JSCL_USER_DOMJQCLEANERSWITCH(values){internals.checkArgsAtMost(arguments.length-1,0);
var v126=this;
return (function(){if (internals.symbolValue(l134)!==l3.value) {internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l154)][internals.xstring(l155)](internals.lisp_to_js(internals.symbolValue(l133))));
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v129){switch(arguments.length-1){case 0:v129=l3.value;
;
default:break;
}var v128=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v128=new internals.Cons(arguments[I+1],v128);
var v130=this;
return l134.value=v129;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l36.fvalue(values,4,l47.fvalue(internals.pv,l3.value,l156));
} else {(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v132){switch(arguments.length-1){case 0:v132=l3.value;
;
default:break;
}var v131=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v131=new internals.Cons(arguments[I+1],v131);
var v133=this;
return l133.value=v132;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l157)][internals.xstring(l158)](internals.lisp_to_js(internals.symbolFunction(l149)),internals.lisp_to_js(10000)));
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v135){switch(arguments.length-1){case 0:v135=l3.value;
;
default:break;
}var v134=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v134=new internals.Cons(arguments[I+1],v134);
var v136=this;
return l134.value=v135;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l65.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l36.fvalue(values,4,l47.fvalue(internals.pv,l3.value,l159));
}return values();
})();
});
FUNC.fname='DOM-JQ-CLEANER-SWITCH';
return FUNC;
})();
l153;
var l160=internals.intern('DOM-JQ-CLEANER-STOP');
var l161=internals.make_lisp_string('window');
var l162=internals.make_lisp_string('clearTimeout');
l160.fvalue=(function(){var FUNC=(function JSCL_USER_DOMJQCLEANERSTOP(values){internals.checkArgsAtMost(arguments.length-1,0);
var v137=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l161)][internals.xstring(l162)](internals.lisp_to_js(internals.symbolValue(l133))));
})();
});
FUNC.fname='DOM-JQ-CLEANER-STOP';
return FUNC;
})();
l160;
var l163=internals.intern('CTRL-BTN-JQ-DOM-CLR');
var l164=internals.make_lisp_string('CLR');
var l165=internals.QIList(internals.make_lisp_string('id'),internals.make_lisp_string('class'),l3);
var l166=internals.QIList(internals.make_lisp_string('ctrl-clr-button-id'),internals.make_lisp_string('tide-button '),l3);
var l167=internals.make_lisp_string('onclick');
l163.value=l123.fvalue(internals.pv,l164,l6.fvalue(internals.pv,l165,l166),l45.fvalue(internals.pv,new internals.Cons(l167,(function JSCL_USER_NIL(values,v139){internals.checkArgs(arguments.length-1,1);
var v140=this;
l153.fvalue(internals.pv);
return values();
}))));
l163;
var l168=internals.intern('CLR-BTN-ON');
var l169=internals.QIList(l168,l3);
l38.fvalue(internals.pv,l169);
l168.fvalue=(function(){var FUNC=(function JSCL_USER_CLRBTNON(values){internals.checkArgsAtMost(arguments.length-1,0);
var v141=this;
return (function(){l27.fvalue(internals.pv,internals.symbolValue(l16),internals.symbolValue(l163));
return values();
})();
});
FUNC.fname='CLR-BTN-ON';
return FUNC;
})();
l168;
var l170=internals.intern('CLR-BTN-OFF');
var l171=internals.QIList(l170,l3);
l38.fvalue(internals.pv,l171);
var l172=internals.make_lisp_string('window');
var l173=internals.make_lisp_string('clearTimeout');
l170.fvalue=(function(){var FUNC=(function JSCL_USER_CLRBTNOFF(values){internals.checkArgsAtMost(arguments.length-1,0);
var v143=this;
return (function(){if (internals.symbolValue(l134)!==l3.value) {internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l172)][internals.xstring(l173)](internals.lisp_to_js(internals.symbolValue(l133))));
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v146){switch(arguments.length-1){case 0:v146=l3.value;
;
default:break;
}var v145=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v145=new internals.Cons(arguments[I+1],v145);
var v147=this;
return l134.value=v146;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l3.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
} else l3.value;
l128.fvalue(internals.pv,internals.symbolValue(l163));
return values();
})();
});
FUNC.fname='CLR-BTN-OFF';
return FUNC;
})();
l170;
var l174=internals.intern('INDENT-LEVEL');
var l175=internals.intern('CHAR','COMMON-LISP');
var l176=internals.intern('EQL','COMMON-LISP');
var l177=internals.intern('ZEROP','COMMON-LISP');
l174.fvalue=(function(){var FUNC=(function JSCL_USER_INDENTLEVEL(values,v148){internals.checkArgs(arguments.length-1,1);
var v149=this;
return (function(){return (function(v151,v152,v153,v154){(function(){return (function(){while ((function(){var x1=v151;
if (typeof x1!='number') throw 'Not a number!';
var x2=v153;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l65.value:l3.value;
})()!==l3.value){if (v152!==l3.value) (function(v156){return l176.fvalue(internals.pv,v156,'\\')!==l3.value?(l3.value,(function(){var v157=1;
var v158=(function(){var x1=v151;
if (typeof x1!='number') throw 'Not a number!';
var x2=v157;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v151=v158;
})()):l176.fvalue(internals.pv,v156,'"')!==l3.value?(l3.value,(v152=l3.value),(function(){var v159=1;
var v160=(function(){var x1=v154;
if (typeof x1!='number') throw 'Not a number!';
var x2=v159;
if (typeof x2!='number') throw 'Not a number!';
return x1-x2;
})();
return v154=v160;
})()):l3.value;
})(l175.fvalue(internals.pv,v148,v151));
 else (function(v161){return l176.fvalue(internals.pv,v161,'(')!==l3.value?(l3.value,(function(){var v162=1;
var v163=(function(){var x1=v154;
if (typeof x1!='number') throw 'Not a number!';
var x2=v162;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v154=v163;
})()):l176.fvalue(internals.pv,v161,')')!==l3.value?(l3.value,(function(){var v164=1;
var v165=(function(){var x1=v154;
if (typeof x1!='number') throw 'Not a number!';
var x2=v164;
if (typeof x2!='number') throw 'Not a number!';
return x1-x2;
})();
return v154=v165;
})()):l176.fvalue(internals.pv,v161,'"')!==l3.value?(l3.value,(function(){var v166=1;
var v167=(function(){var x1=v154;
if (typeof x1!='number') throw 'Not a number!';
var x2=v166;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v154=v167;
})(),v152=l65.value):l3.value;
})(l175.fvalue(internals.pv,v148,v151));
(function(){var v168=1;
var v169=(function(){var x1=v151;
if (typeof x1!='number') throw 'Not a number!';
var x2=v168;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v151=v169;
})();
}return l3.value;
})();
})();
return l177.fvalue(internals.pv,v154)!==l3.value?l3.value:0;
})(0,l3.value,l97.fvalue(internals.pv,v148),0);
})();
});
FUNC.fname='INDENT-LEVEL';
return FUNC;
})();
l174;
var l178=internals.intern('TOPLEVEL');
var l179=internals.make_lisp_string('(');
var l180=internals.make_lisp_string(')');
var l181=internals.make_lisp_string('parents');
var l182=internals.make_lisp_string('jqconsole');
var l183=internals.make_lisp_string('RegisterMatching');
var l184=internals.make_lisp_string('~a> ');
var l185=internals.intern('*PACKAGE*','COMMON-LISP');
var l186=internals.intern('PACKAGE-NAME','COMMON-LISP');
var l187=internals.make_lisp_string('jqconsole-prompt');
var l188=internals.make_lisp_string('jqconsole');
var l189=internals.make_lisp_string('Write');
var l190=internals.make_lisp_string('console');
var l191=internals.make_lisp_string('log');
var l192=internals.make_lisp_string('message');
var l193=internals.make_lisp_string('ERROR[!]: ~a~%');
var l194=internals.make_lisp_string('jqconsole-error');
var l195=internals.make_lisp_string('jqconsole');
var l196=internals.make_lisp_string('Write');
var l197=internals.intern('*HANDLER-BINDINGS*');
var l198=internals.intern('ERROR','COMMON-LISP');
var l199=internals.make_lisp_string('message');
var l200=internals.intern('%ERROR');
var l201=internals.intern('READ-FROM-STRING','COMMON-LISP');
var l202=internals.intern('EVAL-INTERACTIVE');
var l203=internals.make_lisp_string('~S~%');
var l204=internals.make_lisp_string('jqconsole-return');
var l205=internals.make_lisp_string('jqconsole');
var l206=internals.make_lisp_string('Write');
var l207=internals.make_lisp_string('ERROR: ');
var l208=internals.make_lisp_string('jqconsole-error');
var l209=internals.make_lisp_string('jqconsole');
var l210=internals.make_lisp_string('Write');
var l211=internals.intern('!CONDITION-ARGS');
var l212=internals.make_lisp_string('jqconsole-error');
var l213=internals.make_lisp_string('jqconsole');
var l214=internals.make_lisp_string('Write');
var l215=internals.make_lisp_string('jqconsole-error');
var l216=internals.make_lisp_string('jqconsole');
var l217=internals.make_lisp_string('Write');
var l218=internals.make_lisp_string('jqconsole');
var l219=internals.make_lisp_string('Prompt');
l178.fvalue=(function(){var FUNC=(function JSCL_USER_TOPLEVEL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v170=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l182)][internals.xstring(l183)](internals.lisp_to_js(l179),internals.lisp_to_js(l180),internals.lisp_to_js(l181)));
(function(v172){return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l188)][internals.xstring(l189)](internals.lisp_to_js(v172),internals.lisp_to_js(l187)));
})(l47.fvalue(internals.pv,l3.value,l184,l186.fvalue(internals.pv,internals.symbolValue(l185))));
return (function(v196){return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l218)][internals.xstring(l219)](internals.lisp_to_js(l65.value),internals.lisp_to_js(v196),internals.lisp_to_js(internals.symbolFunction(l174))));
})((function JSCL_USER_NIL(values,v173){internals.checkArgs(arguments.length-1,1);
var v174=this;
return (function(){(function(){try{return (function(){try{var v179=[];
return (function(v180){return (function(){var v181=1;
var v182=[];
TBLOOP:while (true){try{switch(v181){case 1:(function(v183){return internals.bindSpecialBindings([l197],[v183],(function(){(function(){var v184=new internals.Cons(l198,(function JSCL_USER_NIL(values,v185){internals.checkArgs(arguments.length-1,1);
var v186=this;
v180=v185;
return (function(){throw new internals.TagNLX(v182,2);
})();
}));
var v187=new internals.Cons(v184,internals.symbolValue(l197));
return l197.value=v187;
})();
return (function(){try{return (function(){throw new internals.BlockNLX(v179,(function(){var v190=l201.fvalue(internals.pv,v173);
var v191=(function(){var FUNC=internals.symbolFunction(l45);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l202.fvalue(values,v190);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
return (function(){return (function(v193,v194){(function(){while (v193!==l3.value){v194=internals.car(v193);
internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l205)][internals.xstring(l206)](internals.lisp_to_js(l47.fvalue(internals.pv,l3.value,l203,v194)),internals.lisp_to_js(l204)));
l3.value;
v193=internals.cdr(v193);
}return l3.value;
})();
return l3.value;
})(v191,l3.value);
})();
})(),'G1036');
})();
}catch (v188){v188=internals.js_to_lisp(v188);
return (internals.isNLX(v188)?l65.value:l3.value)!==l3.value?(function(){throw v188;
})():l200.fvalue(internals.pv,(function(v189){return v189!==l3.value?v189:v188;
})(internals.js_to_lisp((function(){var TMP=v188[internals.xstring(l199)];
return TMP===undefined?l3.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l197));
case 2:(function(){throw new internals.BlockNLX(v179,(function(v195){internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l209)][internals.xstring(l210)](internals.lisp_to_js(l207),internals.lisp_to_js(l208)));
internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l213)][internals.xstring(l214)](internals.lisp_to_js((function(){var F=internals.symbolFunction(l47);
var ARGS=[internals.pv,l3.value];
var TAIL=l211.fvalue(internals.pv,v195);
while (TAIL!=l3.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})()),internals.lisp_to_js(l212)));
return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l216)][internals.xstring(l217)](internals.lisp_to_js(l32.fvalue(internals.pv,'\n')),internals.lisp_to_js(l215)));
})(v180),'G1036');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v182) v181=JUMP.label;
 else throw JUMP;
}}return l3.value;
})();
})(l3.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v179) return CF.values;
 else throw CF;
}})();
}catch (v176){v176=internals.js_to_lisp(v176);
internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l190)][internals.xstring(l191)](internals.lisp_to_js(v176)));
return (function(v178){return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l195)][internals.xstring(l196)](internals.lisp_to_js(l47.fvalue(internals.pv,l3.value,l193,v178)),internals.lisp_to_js(l194)));
})((function(v177){return v177!==l3.value?v177:v176;
})(internals.js_to_lisp((function(){var TMP=v176[internals.xstring(l192)];
return TMP===undefined?l3.value:TMP;
})())));
}})();
l81.fvalue(internals.pv);
return l178.fvalue(values);
})();
}));
})();
});
FUNC.fname='TOPLEVEL';
return FUNC;
})();
l178;
var l220=internals.intern('%%EXPORT');
var l221=internals.intern('NEW');
var l222=internals.intern('OGET');
var l223=internals.intern('DEF!STRUCT');
var l224=internals.intern('JOIN');
var l225=internals.QIList(l221,l222,l63,l223,l224,l3);
l220.fvalue=(function(){var FUNC=(function JSCL_USER_EXPORT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v197=this;
return (function(){return l38.fvalue(values,l225);
})();
});
FUNC.fname='%%EXPORT';
return FUNC;
})();
l220;
var l226=internals.intern('TIDE-GO');
var l227=internals.make_lisp_string('#console-id');
var l228=internals.make_lisp_string('$');
var l229=internals.make_lisp_string('jqconsole');
var l230=internals.make_lisp_string('jqconsole');
var l231=internals.make_lisp_string('bind');
var l232=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l233=internals.intern('STREAM','COMMON-LISP');
var l234=internals.intern('VECTOR','COMMON-LISP');
l226.fvalue=(function(){var FUNC=(function JSCL_USER_TIDEGO(values){internals.checkArgsAtMost(arguments.length-1,0);
var v199=this;
return (function(){return (function(){var v201=l3.value;
l25.fvalue(internals.pv);
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v203){switch(arguments.length-1){case 0:v203=l3.value;
;
default:break;
}var v202=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v202=new internals.Cons(arguments[I+1],v202);
var v204=this;
return v201=v203;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l228)](internals.lisp_to_js(l227)));
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v205=internals.symbolValue(l50);
var v206=l229;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v208){switch(arguments.length-1){case 0:v208=l3.value;
;
default:break;
}var v207=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v207=new internals.Cons(arguments[I+1],v207);
var v209=this;
return (function(){var OBJ=v205;
var TMP=(OBJ[internals.xstring(v206)]=internals.lisp_to_js(v208));
return TMP===undefined?l3.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=(function(){var F=internals.js_to_lisp(v201[internals.xstring(l230)][internals.xstring(l231)](internals.lisp_to_js(v201),internals.lisp_to_js(l68),internals.lisp_to_js(l68)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l73.fvalue(internals.pv);
l232.value=l234.fvalue(internals.pv,l233,(function JSCL_USER_NIL(values,v210){internals.checkArgs(arguments.length-1,1);
var v211=this;
return l64.fvalue(values,l32.fvalue(internals.pv,v210));
}),(function JSCL_USER_NIL(values,v212){internals.checkArgs(arguments.length-1,1);
var v213=this;
return l64.fvalue(values,v212);
}));
l49.fvalue(internals.pv);
return l220.fvalue(values);
})();
})();
});
FUNC.fname='TIDE-GO';
return FUNC;
})();
l226;
var l235=internals.intern('TIDE');
var l236=internals.make_lisp_string('load');
var l237=internals.make_lisp_string('window');
var l238=internals.make_lisp_string('addEventListener');
l235.fvalue=(function(){var FUNC=(function JSCL_USER_TIDE(values){internals.checkArgsAtMost(arguments.length-1,0);
var v214=this;
return (function(){l226.fvalue(internals.pv);
return internals.js_to_lisp(internals.symbolValue(l50)[internals.xstring(l237)][internals.xstring(l238)](internals.lisp_to_js(l236),internals.lisp_to_js((function JSCL_USER_NIL(values){var v218=l3.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v218=new internals.Cons(arguments[I+1],v218);
var v219=this;
return l178.fvalue(values);
}))));
})();
});
FUNC.fname='TIDE';
return FUNC;
})();
l235;
l235.fvalue(internals.pv);
var l239=internals.intern('*MAN-DB*');
var l240=internals.make_lisp_string('man');
var l241=internals.make_lisp_string('man/man0.txt');
var l242=internals.make_lisp_string('dom');
var l243=internals.make_lisp_string('man/dom0.txt');
var l244=internals.intern('MAKE-JS-OBJECT');
l239.value=l244.fvalue(internals.pv,l240,l241,l242,l243);
l239;
var l245=internals.intern('*MAN-DEF-MAN*');
var l246=internals.make_lisp_string('man/man0.txt');
l245.value=l246;
l245;
var l247=internals.intern('MAN-PREFIX');
var l248=internals.make_lisp_string('man-');
l247.fvalue=(function(){var FUNC=(function JSCL_USER_MANPREFIX(values,v220){internals.checkArgs(arguments.length-1,1);
var v221=this;
return (function(){return l63.fvalue(values,l248,v220);
})();
});
FUNC.fname='MAN-PREFIX';
return FUNC;
})();
l247;
var l249=internals.intern('LOAD-MAN');
var l250=internals.intern('SUBSTITUTE','COMMON-LISP');
var l251=internals.intern('SPLIT-STR');
var l252=internals.intern('RES-ALLOC');
var l253=internals.intern('DISPLAY-MAN-TOPIC');
var l254=internals.make_lisp_string("<br> Man: Can't load ~s");
var l255=internals.intern('XHR-RECEIVE');
l249.fvalue=(function(){var FUNC=(function JSCL_USER_LOADMAN(values,v223,v224){internals.checkArgs(arguments.length-1,2);
var v225=this;
return (function(){l255.fvalue(internals.pv,v224,(function JSCL_USER_NIL(values,v227){internals.checkArgs(arguments.length-1,1);
var v228=this;
return (function(){var v229=l3.value;
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v231){switch(arguments.length-1){case 0:v231=l3.value;
;
default:break;
}var v230=l3.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v230=new internals.Cons(arguments[I+1],v230);
var v232=this;
return v229=v231;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l251.fvalue(values,l45.fvalue(internals.pv,'\\'),l250.fvalue(internals.pv,' ',internals.char_from_codepoint(13),l250.fvalue(internals.pv,' ',internals.char_from_codepoint(10),v227)));
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
l252.fvalue(internals.pv,v223,v229);
return l253.fvalue(values,v229);
})();
}),(function JSCL_USER_NIL(values,v233,v234){internals.checkArgs(arguments.length-1,2);
var v235=this;
return l36.fvalue(values,0,l47.fvalue(internals.pv,l3.value,l254,v233));
}));
return values();
})();
});
FUNC.fname='LOAD-MAN';
return FUNC;
})();
l249;
var l256=internals.make_lisp_string('~a~%');
l253.fvalue=(function(){var FUNC=(function JSCL_USER_DISPLAYMANTOPIC(values,v236){internals.checkArgs(arguments.length-1,1);
var v237=this;
return (function(){return (function(){return (function(v240,v241){(function(){while (v240!==l3.value){v241=internals.car(v240);
l47.fvalue(internals.pv,l65.value,l256,v241);
l3.value;
v240=internals.cdr(v240);
}return l3.value;
})();
return l3.value;
})(v236,l3.value);
})();
})();
});
FUNC.fname='DISPLAY-MAN-TOPIC';
return FUNC;
})();
l253;
var l257=internals.intern('CHECK-TOPIC');
l257.fvalue=(function(){var FUNC=(function JSCL_USER_CHECKTOPIC(values,v242){internals.checkArgs(arguments.length-1,1);
var v243=this;
return (function(){return (function(){var v245=internals.js_to_lisp((function(){var TMP=internals.symbolValue(l239)[internals.xstring(v242)];
return TMP===undefined?l3.value:TMP;
})());
return v245!==l3.value?v245:internals.symbolValue(l245);
})();
})();
});
FUNC.fname='CHECK-TOPIC';
return FUNC;
})();
l257;
var l258=internals.intern('MAN');
var l259=internals.QIList(l258,l3);
l38.fvalue(internals.pv,l259);
var l260=internals.intern('RES-REFER');
var l261=internals.intern('NULL','COMMON-LISP');
var l262=internals.intern('NOT','COMMON-LISP');
l258.fvalue=(function(){var FUNC=(function JSCL_USER_MAN(values,v246){internals.checkArgs(arguments.length-1,1);
var v247=this;
return (function(){return (function(){var v249=l247.fvalue(internals.pv,v246);
var v250=l260.fvalue(internals.pv,v249);
if (l262.fvalue(internals.pv,l261.fvalue(internals.pv,v250))!==l3.value) l253.fvalue(internals.pv,v250);
 else l249.fvalue(internals.pv,v249,l257.fvalue(internals.pv,v246));
return values();
})();
})();
});
FUNC.fname='MAN';
return FUNC;
})();
l258;
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
